apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath-yerel
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/veridosyasi"