apiVersion: v1
kind: Pod
metadata:
  name: deneme-secret-volpodu
  labels:
    name: deneme-secret-volpodu
spec:
  containers:
    - name: vol-secret-konteyneri
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: deneme-secret
          mountPath: "/vars/gizli"
          readOnly: true
  volumes:
    - name: deneme-secret
      secret:
        secretName: deneme-secret
