apiVersion: v1
kind: Pod
metadata:
  name: ssh-manifest-podu
  labels:
    name: ssh-manifest-podu
spec:
  containers:
    - name: ssh-secret-konteyneri
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: ssh-secret
          mountPath: "/.ssh/"
          readOnly: true
  volumes:
    - name: ssh-secret
      secret:
        secretName: ssh-key-secret