apiVersion: batch/v1
kind: Job
metadata:
  name: dns-kontrol
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      containers:
      - name: dns-kontrol
        image: busybox
        args:
          - /bin/sh
          - -c
          - sleep 60; date; ping -c 3 -A 8.8.8.8; echo Ping Görevi tamam;date '+%A, %B %d, %Y, %T'
      restartPolicy: Never 
     