apiVersion: batch/v1
kind: Job
metadata:
  name: dns-kontrol
spec:
  template:
    spec:
      containers:
      - name: dns-kontrol
        image: techakademi/fping:1
        command: ["fping"]
        args: ["-d","1.1.1.1","8.8.8.8","208.67.222.222","37.235.1.174"]
      restartPolicy: Never    