apiVersion: v1
kind: PersistentVolume
metadata:
  name: wrprss-yedek-pv
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/yedek/wrprss"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wrprss-yedek-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi