apiVersion: v1
kind: Pod
metadata:
  name: deneme-secret-podu
  labels:
    name: deneme-secret-podu
spec:
  containers:
    - name: secret-konteyneri
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      env:
        - name: KULLANICI
          valueFrom:
            secretKeyRef:
              name: deneme-secret
              key: kullanici
        - name: PAROLA
          valueFrom:
            secretKeyRef:
              name: deneme-secret
              key: parola
