apiVersion: v1
kind: Pod
metadata:
  name: secret-manifest-podu
  labels:
    name: secret-manifest-podu
spec:
  containers:
    - name: kod-secret-konteyneri
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: kod-secret
          mountPath: "/vars/gizli-kod"
          readOnly: true
  volumes:
    - name: kod-secret
      secret:
        secretName: secret-manifest
