apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: merhaba-dunya-replicaset
  labels:
    name: Merhaba-dunya
spec:
  replicas: 3
  selector:
    matchLabels:
      name: Merhaba-dunya
  template:
    metadata:
      labels:
        name: Merhaba-dunya
    spec:
      containers:
      - image: techakademi/merhabadunya:1
        name: merhaba-dunya