apiVersion: v1
kind: Pod
metadata:
  name: dns-kontrol-conf
spec:
  containers:
  - name: dns-kontrol
    image: techakademi/fping:1
    command: ["fping"]
    args: ["-d","$(dns-sunucu-ip1)","$(dns-sunucu-ip2)"]
    env:
      - name: dns-sunucu-ip1
        valueFrom:
          configMapKeyRef:
            name: dns-map
            key: dns1
      - name: dns-sunucu-ip2
        valueFrom:
          configMapKeyRef:
            name: dns-map
            key: dns2
  restartPolicy: Never 